module.exports.descriptors = [
    'Forest',
    'Metro',
    'Chill',
    'Rural',
    'Cascade',
    'Mountain',
    'Peaceful',
    'Redwood',
    'Charming',
    'Urban',
    'Hip',
    'Wine Country',
    'Staycation',
    'Ocean',
    'Sea',
    'Sky',
    'Private',
    'Mellow'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Lakeside',
    'Group Spots',
    'Camping Sites',
    'Historic',
    'Camp',
    'Beach',
    'Backcountry',
    'River',
    'Lake',
    'Full Hookups',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Driveway',
    'Multiple Spots',
    'Cliffs',
    'Dessert'
]